# SPDX-FileCopyrightText: 2022 Jakob Fritz <j.fritz@fz-juelich.de>
#
# SPDX-License-Identifier: CC0-1.0

name: 'Github2lab'
author: 'Jakob Fritz'
description: 'Mirroring a repo to gitlab to use the gitlab-ci'
runs:
  using: "composite"
  steps:
    - run: |
        echo "Mode is unknown. It must be 'mirror', 'get_status', or 'both'. Not '$MODE'"
        exit 1
      shell: bash
      if:  (env.MODE != 'mirror') && (env.MODE != 'get_status') && (env.MODE != 'both')
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: mirror.sh
      shell: bash
      if: (env.MODE == 'mirror') || (env.MODE == 'both')
    - run: get_ci_state.sh
      shell: bash
      if: (env.MODE == 'get_status') || (env.MODE == 'both')
