# SPDX-FileCopyrightText: 2022 Jakob Fritz <j.fritz@fz-juelich.de>
#
# SPDX-License-Identifier: CC0-1.0

name: 'Github2lab'
author: 'Jakob Fritz'
description: 'Mirroring a repo to gitlab to use the gitlab-ci'
runs:
  using: "composite"
  steps:
    - run: |
        echo "Mode is unknown. It must be 'mirror', 'get_status', or 'both'. Not '$MODE'"
        exit 1
      shell: bash
      if:  (env.MODE != 'mirror') && (env.MODE != 'get_status') && (env.MODE != 'both')
      # if:  contains(['mirror', 'get_status', 'both'], $MODE)
    - run: sh ./mirror.sh
      shell: bash
      if: (env.MODE == 'mirror') || (env.MODE == 'both')
    - run: sh ./get_ci_state.sh
      shell: bash
      if: (env.MODE == 'get_status') || (env.MODE == 'both')


# Add variable that can be "mirror", "get_status", or "both" to determine what to do
# Then, only perform that task depending on the variable
# Raise error if value not one of the above

