# SPDX-FileCopyrightText: 2022 Jakob Fritz <j.fritz@fz-juelich.de>
#
# SPDX-License-Identifier: MIT

name: Linting

on: [push, pull_request]

jobs:
  MarkdownLinting:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - uses: actions/checkout@v3
    - name: Lint markdown file
      uses: avto-dev/markdown-lint@v1
      with:
        args: './README.md'
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - uses: actions/checkout@v3
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@6d3f514f44620b9d4488e380339edc0d9bbe2fba
  CheckBashisms:
    runs-on: ubuntu-latest
    container: alpine:3.17
    steps:
    - uses: actions/checkout@v3
    - name: Install checkbashisms
      run: 
        apk add checkbashisms=2.22.2-r0
    - name: run checkbashisms
      run: 
        checkbashisms *.sh
  PythonLinting:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - uses: actions/checkout@v3
    - name: Install dependencies using micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: etc/environment-lint.yml
    - name: Reformat code using black
      shell: bash -l {0}
      run: |
        python -m black *.py --check --diff --color
