# SPDX-FileCopyrightText: 2022 Jakob Fritz <j.fritz@fz-juelich.de>
#
# SPDX-License-Identifier: MIT

name: Mirror and run GitLab CI

on: [push, pull_request_target]

jobs:
  github2lab:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - uses: actions/checkout@v4
    - name: Mirror
      uses: ./
      env:
        MODE: 'mirror'
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "codebase.helmholtz.cloud"
        GITLAB_PROJECT_ID: "6627"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get-CI-State
      uses: ./
      env:
        MODE: 'get_status'
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "codebase.helmholtz.cloud"
        GITLAB_PROJECT_ID: "6627"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get-Artifacts
      uses: ./
      env:
        MODE: 'get_artifact'
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_HOSTNAME: "codebase.helmholtz.cloud"
        GITLAB_PROJECT_ID: "6627"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Mirror and get status
    #   uses: ./
    #   env:
    #     MODE: 'both'
    #     GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    #     FORCE_PUSH: "true"
    #     PRUNE: "true"
    #     GITLAB_HOSTNAME: "codebase.helmholtz.cloud"
    #     GITLAB_PROJECT_ID: "6627"
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Send incorrect mode
    #   uses: ./
    #   env:
    #     MODE: "other"    

